name: CI/CD Pipeline
 push:
  name:
   branches:
    -main
 jobs:
  build:ubuntu-latest
   runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Show Docker images
        run: docker images
